version: 2.1
machine:
  environment:
    DJANGO_SETTINGS_MODULE: datentool.settings_circleci
jobs:
  django testing:
    docker:
      - image: gertzgutscheruemenapp/daviplan:testing
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Resolve Python dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Wait for Postgres to start
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Migrate Test Database
          command: |
            python manage.py migrate --settings=datentool.settings_circleci
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/
      - run:
          name: codecov
          command: |
            python manage.py test --settings=datentool.settings_circleci

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - django testing